services:
  postgress:
    image: postgres:16-alpine
    container_name: kertaskerjarevamp-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - kertaskerjarevamp-network
    volumes:
      - db-data:/var/lib/postgresql/data

#  redis:
#    image: redis:7
#    container_name: kertaskerjarevamp-redis
#    ports:
#      - "${REDIS_PORT}:6379"
#    networks:
#      - kertaskerjarevamp-network

  springboot-app:
    build: .
    container_name: kertaskerjarevamp-app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgress
      - redis
    ports:
      - "8080:8080"
    networks:
      - kertaskerjarevamp-network

networks:
  kertaskerjarevamp-network:
    driver: bridge

volumes:
  db-data:
